### ISSUE TITLE
Doesn't work for languages besides English

### ISSUE THREAD

**Issue by MatteoGauthier** [flybayer/twitter-bookmarks-search#1]
![image](https://user-images.githubusercontent.com/32040951/69375081-bf7e0400-0ca7-11ea-8f29-3ea8337fc554.png)
![image](https://user-images.githubusercontent.com/32040951/69375144-e4727700-0ca7-11ea-9b33-817db62402a0.png)
Nothing happen

**Comment by stepney141** [comment]
I'm facing the same problem.
I installed the extension on Chrome 80.0.3987.149 and Firefox 74.0, but nothing happened at all.
Nothing changed in Twitter and my browsers though I clicked the extension's icon at the menu bar and restarted the browsers.

**Comment by flybayer** [comment]
This is a known issue for languages besides english. I don't have time at the moment to fix it, but anyone is welcome to submit a PR!

**Comment by akaguny** [comment]
this issue was complete with #7 , pls check this @MatteoGauthier

**Comment by MatteoGauthier** [comment]
@akaguny Thanks a lot !! 😉

**Comment by flybayer** [comment]
Published in stores now
