### ISSUE TITLE
Results no longer scroll properly.

### ISSUE THREAD

**Issue by Kaleidosium** [flybayer/twitter-bookmarks-search#14]
I'm not sure how to screenshot it, but if you search for something with more than one result, it cannot scroll any further than the latest result, People on the Chrome Web Store actually complained about this for a bit.
![image](https://user-images.githubusercontent.com/39834015/119939353-ebbec300-bfb7-11eb-8985-ac55d6443912.png)

**Comment by motdde** [comment]
Hello @flybayer, kindly take a look at PR #15. I hope if fix this issue, if not kindly recommend how to improve it.

Thank you.

**Comment by flybayer** [comment]
Closed by #15

**Comment by motdde** [comment]
Thanks for merging @flybayer
