### ISSUE TITLE
Search-bar no longer appears

### ISSUE THREAD

**Issue by Kaleidosium** [flybayer/twitter-bookmarks-search#16]
Just as the scrolling bug was fixed, Twitter decided to break the Extension again. Now the search-bar doesn't even appear anymore.
![image](https://user-images.githubusercontent.com/39834015/126727968-de0e32fd-7972-425b-a2fe-fc66a6b8ef21.png)

**Comment by motdde** [comment]
Twitter updated their markup recently. I have a working version on my Mac that I loaded unpacked, but there is a bug with my selector. it has to do with checking for the childNodes of an element before it's loaded on the /bookmarks route.

![image](https://user-images.githubusercontent.com/12215060/126849318-5e29c9e2-1fec-493f-a785-329fce9149e0.png)

Here is a SC of the working version:
![image](https://user-images.githubusercontent.com/12215060/126849390-639de314-ae49-4543-898e-4c27cef9effa.png)



I can do a PR if that's ok.

**Comment by motdde** [comment]
@flybayer Kindly review #17

**Comment by flybayer** [comment]
New version submitted to chrome store

**Comment by flybayer** [comment]
Closed by #17

**Comment by motdde** [comment]
@flybayer How else would you fix the bug? How can I delay that variable declaration for getTitleContainer or wait for the bookmarks page to be fully loaded before it's defined?

**Comment by flybayer** [comment]
@motdde I didn't look closely, but it's working so that's the main thing!

**Comment by motdde** [comment]
😂  Thanks, @flybayer.

Your work on Blitz.js is phenomenal.

I want to work with you at @Flightcontrolhq. I am seeking an opportunity to join a team where I can tinker, solve problems, and get my software engineering skills sharpened.

It would be an honour to work with you. I look forward to hearing back from you.

Cheers.

**Comment by flybayer** [comment]
@motdde thanks! Not currently hiring, but in the future we'll post any available jobs as we have them.

**Comment by motdde** [comment]
Thanks.
