### ISSUE TITLE
"Oh snap, no bookmarked tweets are loaded. Wait a little longer or reload to try again"

### ISSUE THREAD

**Issue by davidelson23** [flybayer/twitter-bookmarks-search#4]
Hi, I'm getting the error message above on both Chrome & Firefox. 
Anything I'm doing wrong? 
Thanks in advance!

**Comment by flybayer** [comment]
Uh oh 😬 it's broken for me too. Twitter probably updated something

**Comment by lesander** [comment]
I've observed the same problem. Console shows: `Unchecked runtime.lastError: The message port closed before a response was received.` A quick F5 shows the below:

![image](https://user-images.githubusercontent.com/4174509/81392193-96024900-911e-11ea-8988-f6d2e2fee689.png)

**Comment by akaguny** [comment]
Actually? In my case bookmark search work fine

**Comment by flybayer** [comment]
Works for me now too

**Comment by BerkhanEminsoy** [comment]
Petition to open this issue again? I'm getting this for some reason...

**Comment by RonRichman** [comment]
Agree, please reopen

**Comment by flybayer** [comment]
Can you inspect your network tab of devtools and see if there's an issue with adblocker or something? The bug reported by the OP has been fixed. So I'm suspecting something in our environment.

**Comment by RonRichman** [comment]
@flybayer it was Adblockplus! Thanks so much for your pointer to resolve this issue!

**Comment by pmaheshchauhan** [comment]
Still not working for me

**Comment by DeadPigman17** [comment]
It's not working for me either.
