### ISSUE TITLE
Extension Not Found in Mozilla Firefox

### ISSUE THREAD

**Issue by SimeonOA** [flybayer/twitter-bookmarks-search#5]
Hi,

Thank you so much for this extension.

I just tried adding it to Firefox but I was directed to a page that said the extension is no longer available.

Have you removed the extension from Firefox?

**Comment by flybayer** [comment]
@SimeonOA I have not removed it, but perhaps firefox took it down for some reason.

**Comment by Shadowspear123** [comment]
Same here, can't find it on the firefox add-ons website anywhere.

**Comment by flybayer** [comment]
Here it is!

https://addons.mozilla.org/en-US/firefox/addon/twitter-bookmarks-search/

I don't know why it doesn't show in search
