### ISSUE TITLE
[ Bookmark Search ] field does not show In Chromium 

### ISSUE THREAD

**Issue by sfd99** [flybayer/twitter-bookmarks-search#6]
-  Chromium version 86.0.4240.183 (Official Build) snap (64-bit)
 -  Ubuntu Linux 20.04 (latest), 
 -  acorn/twitter-bookmarks-search:  Version 5.

The **[ Bookmark Search ]** field 
DOES show up _occasionally_,
but ... generaly
_it does not show up_ at all
when I select "Bookmarks" in Twitter's left-side Menu.

**_NOTE:_**
If I REload the Twitter Bookmarks webpage ,
the **[ Bookmark Search ]** field  
will show / flash at the top of the page _for less than a second_,
and then disappear!. 

The very few times the **[ Bookmark Search ]** field 
shows up, it works beautifully!! .

How to make the **[ Bookmark Search ]** field
_ALWAYS_ show up 
when I am in Twitter's Bookmarks page?:
https://twitter.com/i/bookmarks

_Help!_
**SFd99
San Francisco**

**Comment by akaguny** [comment]
screenshot pls and browser log (f12)
