### ISSUE TITLE
Search causes a 405 Error

### ISSUE THREAD

**Issue by Kaleidosium** [flybayer/twitter-bookmarks-search#9]
When trying to search bookmarks using this extension as of the time of writing, it returns an Error `alert()` and 405 error in the console, If collect errors is enabled in the Extension's settings page.

Images:
![image](https://user-images.githubusercontent.com/39834015/115972661-f251b900-a579-11eb-8f04-6f1d4832650d.png)
![image](https://user-images.githubusercontent.com/39834015/115972667-fa115d80-a579-11eb-8583-85c06a1f21fb.png)

**Comment by flybayer** [comment]
I'm seeing the same thing. Twitter must have changed something on the backend. Hopefully we can work around it.

PRs welcome
